### ISSUE TITLE
phylogeo compatibility with other maps

### ISSUE THREAD

**Issue by StephanieKH** [zachcp/phylogeo#20]
I am using phyloseq and am very interested in using your R package phylogeo.  I have been playing around with phylogeo and while I can plot my points on the full map, I can't seem to get a good close-up/regional view because my sample sites are in Hawaii.  The map world2Hires (mapdata package) would be ideal for my needs, but it seems that there isn't a way to specify which map is being used in the map_phyloseq command.  Is phylogeo compatible with the world2Hires map?  I would greatly appreciate any help you can give in pointing me in the right direction.

**Comment by zachcp** [comment]
Stephanie,

Thank you for writing. phylogeo's maps are all made with ggplot's `map_coord()` function and therefore has the same sorts of issues that  `map_coord` has when you deviate too far from a simple map. For your case it looks like there are maybe two separate issue - getting higher resolution shapes of the Hawaiian islands and finding a good way to zoom in on your data. I will look into the first to see how it can be done and have outlined the three ways you can zoom in phylogeo:

##### Use the “region” command:
This won’t yield a very useful map unless your points are well distributed around one of the regions (countries). Hawaii won’t look good here at all.

```
map_phyloseq(mountainsoil, region=“china”) or
map_phyloseq(mountainsoil, region=“USA”)
```

##### Use xlim and ylim to modify the coord_map function:
```
map_phyloseq(mountainsoil) + coord_map(xlim=c(-180,-140),ylim=c(10,30))
```
This will correctly get you in the neighborhood of Hawaii but doesn’t look very good for two reasons: low resolution borders (which we could fix if we added the hires data), and an artifact of the way ggplot does projections that is causing a grey background. I would love for number 2 to be fixed because it would be a general solution and can take a look at where the distortion comes from - but I can't really promise anything here. 

##### Use the leafletmaps branch of phylogeo. 
This is my best recommendation for your problem. Instead of using ggplot on the backend I draw the points and lines using an [interactive javascript library](https://github.com/rstudio/leaflet) that lets you zoom in as close/far as you like. It is far better for exploratory analysis and is not in the main package only because one of the dependencies (rsudio/leaflet) is not yet on CRAN.  However it is straightforward to install. For the best interactive experience I would recommend using RStudio.
```
library(devtools)
install_github("zachcp/phylogeo", ref="leafletmaps”)
library(phylogeo)
htmlmap_phyloseq(mountainsoil)
htmlmap_network(mountainsoil)
```

**Comment by zachcp** [comment]
@StephanieKH 

I realize this is quite late and you probably have moved on but I have just modified the ggplot-based plotting function to allow use of the mapdata maps. You can pass in a `mapdata` value to call the map of your choosing as in the following:
```
map_phyloseq(mountainsoil, mapdata="worldHires")
```

Just a note, the hires maps are much slower to use.

**Comment by StephanieKH** [comment]
@zachcp

Thank you for taking my request into account.  I will definitely give it
another go.

Stephanie
